### ISSUE TITLE
[Bug] <title>cookie登录无法登录显示获取bdstoken失败 新获取的cookie也不行，之前登录上的号可正常使用

### ISSUE THREAD

**Issue by Baolongxing** [PanDownload-Fix/PanDownload-Fix#13]
### Verify steps

- [X]  如果你可以自己 debug 并解决的话，提交 PR 一起完善帮助文档吧 Is this something you can **debug and fix**? Send a pull request! Bug fixes and documentation fixes are welcome. 
- [X]  我已经在 [Issue Tracker](https://github.com/PanDownload-Fix/PanDownload-Fix/labels/bug) 中找过我要提出的问题 I have searched on the [issue tracker](https://github.com/PanDownload-Fix/PanDownload-Fix/labels/bug) for a related issue. 
- [X]  我已经使用的是最新版本了，问题依旧存在 I have using the latest version, and the issue still exists. 
- [X]  我已经仔细看过 [Documentation](https://pandownload.net/) 并无法自行解决问题 I have read the [documentation](https://pandownload.net/) and was unable to solve the issue. 
- [X]  这是 PanDownload 本体的问题，并非我所使用的第三方 Lua 的问题（除了“默认”接口外都为第三方 Lua）的特定问题 This is an issue of the PanDownload *per se*, not to the others third party Lua. 

### PanDownload version

官网最新版1.6

### Reproduction steps

```yaml
cookie登录无法登录显示获取bdstoken失败 新获取的cookie也不行，之前登录上的号可正常使用
```

### PanDownload log

```shell
无
```

### Description

cookie登录无法登录显示获取bdstoken失败 新获取的cookie也不行，之前登录上的号可正常使用 @

**Comment by icy37785** [comment]
cookie正确就一定能登陆，登录不了就是cookie有问题。cookie的问题自行检查。
