### ISSUE TITLE
[Feature] 没有看到源码

### ISSUE THREAD

**Issue by jmuchch** [PanDownload-Fix/PanDownload-Fix#15]
### Verify steps

- [X]  我已经在 [Issue Tracker](https://github.com/PanDownload-Fix/PanDownload-Fix/labels/feature%20request) 中找过我要提出的请求 I have searched on the [issue tracker](https://github.com/PanDownload-Fix/PanDownload-Fix/labels/feature%20request) for a related feature request. 
- [X]  我已经仔细看过 [Documentation](https://pandownload.net/) 并无法自行解决问题 I have read the [documentation](https://pandownload.net/) and was unable to solve the issue. 

### Description

脚本中或其他地方没有看到源码

**Comment by FalseMario** [comment]
@jmuchch 沒理解，你是想看到什麽源代碼。

**Comment by jmuchch** [comment]
比如，调用百度网盘的API，以及下面这个界面的源码







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月2日(星期天) 晚上9:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PanDownload-Fix/PanDownload-Fix] 没有看到源码[Feature] <title&gt; (Issue #15)





 
@jmuchch 沒理解，你是想看到什麽源代碼。

**Comment by FalseMario** [comment]
@jmuchch 哪裏都沒提過這些部分是開源部分。

**Comment by jmuchch** [comment]
好吧，我以为是个开源项目呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月2日(星期天) 晚上9:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PanDownload-Fix/PanDownload-Fix] 没有看到源码[Feature] <title&gt; (Issue #15)





 
@jmuchch 哪裏都沒提過這些部分是開源部分。

**Comment by jmuchch** [comment]
就是想看看是怎么实现的，怎么编译，怎么打包


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PanDownload-Fix/PanDownload-Fix"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月2日(星期天) 晚上9:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PanDownload-Fix/PanDownload-Fix] 没有看到源码[Feature] <title&gt; (Issue #15)





 
@jmuchch 哪裏都沒提過這些部分是開源部分。
